// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eSurvey.Infrastructure.ApplicationDbContext;

#nullable disable

namespace eSurvey.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240905084457_Initial3")]
    partial class Initial3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eSurvey.Domain.Entities.CompletedSurveysTable", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SurveyJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Survey_JsonFormat");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Template_Id");

                    b.Property<string>("UserIDNP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("User_IDNP");

                    b.HasKey("Id")
                        .HasName("CompletedSurvey_Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("CompletedSurveysTable", (string)null);
                });

            modelBuilder.Entity("eSurvey.Domain.Entities.SurveyTemplatesTable", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TemplateJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Survey_JsonFormat");

                    b.HasKey("Id")
                        .HasName("SurveyTemplate_Id");

                    b.ToTable("SurveyTemplatesTable", (string)null);
                });

            modelBuilder.Entity("eSurvey.Domain.Entities.CompletedSurveysTable", b =>
                {
                    b.HasOne("eSurvey.Domain.Entities.SurveyTemplatesTable", null)
                        .WithMany("CompletedSurveys")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eSurvey.Domain.Entities.SurveyTemplatesTable", b =>
                {
                    b.Navigation("CompletedSurveys");
                });
#pragma warning restore 612, 618
        }
    }
}
